---
title: "Thesis code knit"
output:
  pdf_document: default
  html_document: default
date: "2024-01-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, warning=FALSE}
library(pacman)
p_load(haven, tidyverse, prodest, estprod, plm)
```


```{r}
#load 2009-2013 Enterprise Survey data
data1 <- read_dta("C:\\Users\\Aayush\\Documents\\Nepal_2009_2013.dta")

```

```{r}
data2 <- data1 %>%
  # Select only manufacturing firm
  filter(a0 == 1) %>%
  #Select only rows valid for balanced panel
  group_by(id2009) %>%
  filter(all(c(2009, 2013) %in% year)) %>%
  ungroup()
```

```{r}
data3 <- data2 %>% 
  
  #select necessary columns for data analysis
  select(year, id2009, d2, n7a, n2a, n2e,e11,b7,k8, a6b,j30c,j30a,l1,b5,l4a,b7,d3c,e6,b2b,c30a,
         e1) %>% 
  
  #filter rows with values greater than or equal to 0
  filter(if_all(c(d2,n7a,n2a,n2e,e11,b7,k8,a6b,j30c,j30a,l1,b5,l4a,b7,d3c,e6,b2b,c30a,e1), ~.>= 0)) %>% 
  
  #adding no. of years of operation column to the data
  mutate(yofop = ifelse(year == 2009, 2009 - b5, ifelse(year == 2013, 2013 - b5, NA))) %>%  
  
  #renaming columns
  rename(sales = d2, capital = n7a, labor = n2a, interm = n2e, ID = id2009, Informal="e11", Experience="b7", Credit="k8",
          Size="a6b", Foreigntech="e6", Bussiness_permit="j30c", Tax_burden="j30a", local="e1") %>% 
  
  #take natural log of certain columns
  mutate(across(c(sales, capital,labor,interm), ~log(.))) %>% 
  
  #Adjust for inflation for monetary values
  mutate(
    across(c(sales, capital, labor, interm),
           ~ifelse(year == 2013, (./142.52)*100, .))) %>% 
  
  #Create dummy variables out of ordinal variables
  mutate(across(c(Informal, Credit, local, Foreigntech),
           ~case_when(. == 1 ~ 1,
                      TRUE ~ 0)),
    a6b = case_when(Size %in% c(1,2) ~ 1,
                    TRUE ~ 0))
  
  
```


```{r}
#levinsohn model
levinsohn_model <- levinsohn_petrin(data = data3, sales ~ labor | capital | interm,
                  id = "ID", time = "year", bootstrap = TRUE)
#olleypakes
olleypakes_model <- olley_pakes(data = data3, sales ~ labor | capital | interm,
                 id = "ID", time = "year", bootstrap = TRUE)

```

```{r}
#filter again with coefficients
data4 <- data3%>% 
  mutate(va=sales-interm) %>% 
  mutate(logtfp=va-((levinsohn_model$t0[1])*labor)-((levinsohn_model$t0[2])*capital)) %>% 
  mutate(avetfp=scale(logtfp)) 

```


